#!/bin/sh

echo "Loading device tree overlay for PRU-ADC..."

cp /root/AcquisitionSystem/ADC/EBB-PRU-ADC-00A0.dtbo /lib/firmware

cd /lib/firmware
echo EBB-PRU-ADC > /sys/devices/bone_capemgr.9/slots
cat /sys/devices/bone_capemgr.9/slots
echo "done"
